# Generated by Django 5.2.15 on 2026-07-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0006_stripeevent_rename_subscriptionplan_stripe_plan_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="trial_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
