# Generated by Django 5.2.14 on 2026-05-10 16:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_stripe_customer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=core.models.image_upload_path)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
