# Generated by Django 5.2.14 on 2026-05-27 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("users", "0009_player_tutorial_steps_seen_tutorialstep_youtube_url"),
        ("users", "0010_tutorialstep_image_fk"),
    ]

    dependencies = [
        ("core", "0003_image"),
        ("users", "0008_tutorialstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="tutorial_steps_seen",
            field=models.ManyToManyField(
                blank=True, related_name="seen_by", to="users.tutorialstep"
            ),
        ),
        migrations.AddField(
            model_name="tutorialstep",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="tutorialstep",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/tutorialstep/"
            ),
        ),
        migrations.AlterField(
            model_name="tutorialstep",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RemoveField(
            model_name="tutorialstep",
            name="image",
        ),
        migrations.RemoveField(
            model_name="tutorialstep",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="tutorialstep",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tutorialstep",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="tutorialstep",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutorial_steps",
                to="core.image",
            ),
        ),
    ]
