# Generated by Django 5.2.14 on 2026-05-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_tutorialstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="tutorial_steps_seen",
            field=models.ManyToManyField(
                blank=True, related_name="seen_by", to="users.tutorialstep"
            ),
        ),
        migrations.AddField(
            model_name="tutorialstep",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="tutorialstep",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/tutorialstep/"
            ),
        ),
        migrations.AlterField(
            model_name="tutorialstep",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
