# Generated by Django 5.2.14 on 2026-05-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_player_tutorial_steps_seen_tutorialstep_youtube_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorialstep",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/tutorialstep/"
            ),
        ),
    ]
