# Generated by Django 5.2.15 on 2026-07-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0009_player_tutorial_steps_seen_tutorialstep_youtube_url_squashed_0010_tutorialstep_image_fk",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("signup_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("invited", "Invited"),
                            ("redeemed", "Redeemed"),
                            ("removed", "Removed"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=10,
                    ),
                ),
                (
                    "invite_token",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["signup_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["status", "signup_timestamp"],
                        name="users_waitl_status_5c3a47_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["waiting", "invited"])),
                        fields=("email",),
                        name="unique_active_waitlist_email",
                    )
                ],
            },
        ),
    ]
