# Generated by Django 5.2.14 on 2026-05-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("free_timer_limit_seconds", models.IntegerField(default=1800)),
            ],
            options={
                "verbose_name": "Game settings",
                "verbose_name_plural": "Game settings",
            },
        ),
    ]
