# Generated by Django 5.2.14 on 2026-05-27 18:37

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.BinaryField()),
                ("filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream", max_length=100
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                storage=core.models.DatabaseFileStorage(), upload_to=""
            ),
        ),
    ]
