# Generated by Django 5.2.14 on 2026-06-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_storedfile_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="trial_period_days",
            field=models.IntegerField(default=14),
        ),
    ]
