# Generated by Django 5.2.14 on 2026-06-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_trial_period_days_to_gamesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="task_activity_xp_multiplier",
            field=models.DecimalField(decimal_places=2, default="1.25", max_digits=5),
        ),
        migrations.AddField(
            model_name="gamesettings",
            name="task_completion_xp",
            field=models.IntegerField(default=100),
        ),
    ]
