# Generated by Django 5.2.15 on 2026-07-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_gamesettings_task_xp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="registration_cap",
            field=models.IntegerField(default=1000000000),
        ),
    ]
