# Generated by Django 5.2.15 on 2026-07-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_gamesettings_waitlist_nudges_enabled_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="registration_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
