# Generated by Django 5.2.15 on 2026-07-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_gamesettings_registration_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="self_serve_registration",
            field=models.BooleanField(default=False),
        ),
    ]
