# Generated by Django 5.2.15 on 2026-07-09 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_announcement_playerannouncementstate"),
        ("core", "0010_gamesettings_self_serve_registration"),
    ]

    operations = []
