# Generated by Django 5.2.16 on 2026-07-18 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0004_rename_field_to_field_shelter"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("fallow", "Fallow"),
                            ("growing", "Growing"),
                            ("ready", "Ready"),
                        ],
                        default="fallow",
                        max_length=20,
                    ),
                ),
                ("planted_at", models.DateTimeField(blank=True, null=True)),
                ("ready_yield", models.FloatField(blank=True, null=True)),
                ("harvested_amount", models.FloatField(default=0)),
                ("last_processed_on", models.DateField(blank=True, null=True)),
                (
                    "shelter_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_crops",
                        to="locations.building",
                    ),
                ),
                (
                    "subzone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_crop",
                        to="locations.subzone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "good_type",
                    models.CharField(choices=[("wheat", "Wheat")], max_length=20),
                ),
                ("quantity", models.FloatField(default=0)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_stocks",
                        to="locations.building",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("building", "good_type"),
                        name="uniq_goods_stock_per_building",
                    )
                ],
            },
        ),
    ]
