# Generated by Django 5.2.16 on 2026-07-18 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0001_initial"),
        ("locations", "0005_alter_interiorspace_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsstock",
            name="good_type",
            field=models.CharField(
                choices=[("wheat", "Wheat"), ("flour", "Flour")], max_length=20
            ),
        ),
        migrations.CreateModel(
            name="GoodsConversionState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_processed_on", models.DateField(blank=True, null=True)),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_state",
                        to="locations.building",
                    ),
                ),
            ],
        ),
    ]
