"""
Import a village generated by watabou's city/village generator
(https://watabou.github.io/city-generator/), exported as JSON, into the
game world.

The export isn't standard GeoJSON - each top-level "feature" is keyed by a
fixed `id` (earth/roads/buildings/districts/...) rather than carrying a
`properties` bag - so it's parsed by id below rather than through a generic
GeoJSON loader. Coordinates are in the generator's own local unit space,
centred near the origin; that space is treated as flat metres and
translated onto a chosen point in the game world's SRID 3857 plane, the
same "just metres, no real georeferencing" convention the rest of
locations/ already uses (see MAX_BBOX_AREA_SQ_M in locations/utils.py).

This only creates static geometry - PopulationCentre, Building, Road, and
the Node graph's CENTRE/BUILDING/BUILDING_ENTRANCE points. It deliberately
does not generate Path edges: Path is the movement/pathfinding graph and
Road is just the drawn street, so wiring the graph is left to the existing
`generate_paths` command (see the `--generate-paths` flag on
import_watabou_village's management command) rather than trying to derive
walkable edges from arbitrary imported road geometry.
"""

from django.contrib.gis.geos import LineString, Point, Polygon
from django.db import transaction

from locations.management.commands.spawn_villages import (
    compute_building_entrance_point,
)
from locations.models import Building, Node, PopulationCentre, Road

# watabou's roads sometimes omit a per-geometry "width" - fall back to the
# export's own top-level default (the "values" feature's roadWidth) when
# that happens, matching how the generator itself would render them.
DEFAULT_ROAD_WIDTH = 6.0


def _feature_by_id(data: dict, feature_id: str) -> dict | None:
    for feature in data.get("features", []):
        if feature.get("id") == feature_id:
            return feature
    return None


def _close_ring(ring):
    """watabou rings aren't guaranteed closed (first point != last); GEOS
    Polygons require it, so append the start point back on if needed."""
    points = [tuple(pt) for pt in ring]
    if points[0] != points[-1]:
        points.append(points[0])
    return points


def _translate_polygon(coordinates, offset, srid=3857) -> Polygon:
    dx, dy = offset
    rings = [
        [(x + dx, y + dy) for x, y in _close_ring(ring)] for ring in coordinates
    ]
    return Polygon(*rings, srid=srid)


def _translate_linestring(coordinates, offset, srid=3857) -> LineString:
    dx, dy = offset
    points = [(x + dx, y + dy) for x, y in coordinates]
    return LineString(points, srid=srid)


@transaction.atomic
def import_watabou_village(data: dict, *, name: str, origin: Point) -> PopulationCentre:
    """
    Build a PopulationCentre (+ Buildings, Roads, and the CENTRE/BUILDING/
    BUILDING_ENTRANCE node graph) from a watabou city-generator export,
    positioned so the village's district boundary is centred on `origin`.
    """
    values = _feature_by_id(data, "values") or {}
    default_road_width = values.get("roadWidth", DEFAULT_ROAD_WIDTH)

    buildings_feature = _feature_by_id(data, "buildings") or {"coordinates": []}
    roads_feature = _feature_by_id(data, "roads") or {"geometries": []}
    districts_feature = _feature_by_id(data, "districts")
    earth_feature = _feature_by_id(data, "earth")

    # Prefer the named district (the actual town/village extent) over the
    # "earth" feature, which is just the generator's outer terrain-tile clip
    # boundary - much larger than the settlement itself.
    if districts_feature and districts_feature.get("geometries"):
        district_geom = districts_feature["geometries"][0]
    elif earth_feature:
        district_geom = earth_feature
    else:
        raise ValueError("watabou export has neither a district nor an earth boundary")

    raw_centroid = Polygon(_close_ring(district_geom["coordinates"][0])).centroid
    offset = (origin.x - raw_centroid.x, origin.y - raw_centroid.y)

    boundary = _translate_polygon(district_geom["coordinates"], offset)

    population_centre = PopulationCentre.objects.create(
        name=name,
        location=origin,
        boundary=boundary,
    )

    Node.objects.get_or_create(
        name=f"Central node of settlement {population_centre.name}",
        population_centre=population_centre,
        defaults={"location": population_centre.location, "kind": Node.Kind.CENTRE},
    )

    for i, polygon_coords in enumerate(buildings_feature.get("coordinates", [])):
        footprint = _translate_polygon(polygon_coords, offset)
        building = Building.objects.create(
            name=f"Building {i + 1} of ({name})",
            building_type="residential",
            location=footprint.centroid,
            footprint=footprint,
            population_centre=population_centre,
        )
        Node.objects.get_or_create(
            building=building,
            kind=Node.Kind.BUILDING,
            defaults={
                "name": f"Node for {building.name}",
                "location": building.location,
            },
        )
        entrance_point = compute_building_entrance_point(
            building.footprint, building.location
        )
        Node.objects.get_or_create(
            building=building,
            kind=Node.Kind.BUILDING_ENTRANCE,
            defaults={
                "name": f"Entrance for {building.name}",
                "location": entrance_point,
            },
        )

    for geometry in roads_feature.get("geometries", []):
        if geometry.get("type") != "LineString":
            continue
        Road.objects.create(
            population_centre=population_centre,
            geom=_translate_linestring(geometry["coordinates"], offset),
            width=geometry.get("width", default_road_width),
        )

    return population_centre
