# Generated by Django 5.2.14 on 2026-06-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server_management", "0003_featureflag_access_groups"),
        ("server_management", "0003_maintenancewindow_scheduled_task_ids"),
    ]

    operations = []
