# Generated by Django 5.2.14 on 2026-06-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0004_playeractivity_group_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="first_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
