# Generated by Django 5.2.16 on 2026-07-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0011_characterneeds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterlocation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="characterneeds",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
