# Generated by Django 5.2.16 on 2026-07-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_disable_wander_tick_periodic_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="building_type",
            field=models.CharField(
                choices=[
                    ("residential", "Residential"),
                    ("granary", "Granary"),
                    ("inn", "Inn"),
                    ("mill", "Mill"),
                    ("bakery", "Bakery"),
                    ("communal", "Communal"),
                    ("field", "Field"),
                ],
                default="residential",
                max_length=50,
            ),
        ),
    ]
