# Generated by Django 5.2.16 on 2026-07-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_rename_field_to_field_shelter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interiorspace",
            name="usage",
            field=models.CharField(
                choices=[
                    ("living", "Living"),
                    ("sleeping", "Sleeping"),
                    ("hygiene", "Hygiene"),
                    ("kitchen", "Kitchen"),
                    ("storage", "Storage"),
                    ("grain_storage", "Grain Storage"),
                    ("flour_storage", "Flour Storage"),
                    ("workshop", "Workshop"),
                    ("animals", "Animals"),
                    ("meeting", "Meeting"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
