# Generated by Django 5.2.16 on 2026-07-30 13:56

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import LineString
from django.db import migrations


def backfill_path_geom(apps, schema_editor):
    Path = apps.get_model("locations", "Path")
    for path in Path.objects.select_related("from_node", "to_node").iterator():
        if path.from_node_id is None or path.to_node_id is None:
            continue
        try:
            path.geom = LineString(
                path.from_node.location, path.to_node.location, srid=3857
            )
        except Exception:
            continue
        path.save(update_fields=["geom"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_alter_interiorspace_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="path",
            name="geom",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, null=True, srid=3857
            ),
        ),
        migrations.RunPython(backfill_path_geom, noop_reverse),
    ]
