# Generated by Django 5.2.16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_path_geom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=3857),
                ),
                (
                    "width",
                    models.FloatField(default=6.0, help_text="Road width in metres"),
                ),
                (
                    "population_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roads",
                        to="locations.populationcentre",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="road",
            index=models.Index(
                fields=["population_centre"], name="road_pc_idx"
            ),
        ),
    ]
