# Generated by Django 5.2.16 on 2026-08-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_path_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
