# Generated by Django 5.2.16 on 2026-08-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_alter_building_name"),
        ("locations", "0007_road"),
    ]

    operations = []
